{% set version = "2.3.1" %}

package:
  name: munch
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/munch/munch-{{ version }}.tar.gz
  sha256: fc64a4aeb47e34ff1125f69af3cf3f59e51554b96dbaa2b720c6fb6c9e47a551

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - six

test:
  imports:
    - munch

about:
  home: http://github.com/Infinidat/munch
  license: MIT
  license_file: LICENSE.txt
  summary: 'A dot-accessible dictionary (a la JavaScript objects).'

extra:
  recipe-maintainers:
    - ocefpaf
